import type { Game } from '@/structures'

export const GAMES: Record<string, Game> = {
    '2026-07-15': {
        start_player_id: '26485',
        start_player_name: 'Jérôme Boateng',
        end_player_id: '60444',
        end_player_name: 'Thiago Alcántara',
        contributor: 'jarvis',
    },
    '2026-07-14': {
        start_player_id: '31909',
        start_player_name: 'Toni Kroos',
        end_player_id: '7476',
        end_player_name: 'Xabi Alonso',
        contributor: 'jarvis',
    },
    '2026-07-13': {
        start_player_id: '39728',
        start_player_name: 'Mats Hummels',
        end_player_id: '74842',
        end_player_name: 'Mario Götze',
        contributor: 'jarvis',
    },
    '2026-07-12': {
        start_player_id: '58358',
        start_player_name: 'Thomas Müller',
        end_player_id: '4360',
        end_player_name: 'Arjen Robben',
        contributor: 'jarvis',
    },
    '2026-07-11': {
        start_player_id: '10',
        start_player_name: 'Miroslav Klose',
        end_player_id: '35664',
        end_player_name: 'Mesut Özil',
        contributor: 'jarvis',
    },
    '2026-07-10': {
        start_player_id: '2514',
        start_player_name: 'Bastian Schweinsteiger',
        end_player_id: '63',
        end_player_name: 'Michael Ballack',
        contributor: 'jarvis',
    },
    '2026-07-09': {
        start_player_id: '433177',
        start_player_name: 'Bukayo Saka',
        end_player_id: '357565',
        end_player_name: 'Rodri',
        contributor: 'jarvis',
    },
    '2026-07-08': {
        start_player_id: '580195',
        start_player_name: 'Jamal Musiala',
        end_player_id: '581678',
        end_player_name: 'Jude Bellingham',
        contributor: 'jarvis',
    },
    '2026-07-07': {
        start_player_id: '72347',
        start_player_name: 'Franz Beckenbauer',
        end_player_id: '72343',
        end_player_name: 'Karl-Heinz Rummenigge',
        contributor: 'jarvis',
    },
    '2026-07-06': {
        start_player_id: '17259',
        start_player_name: 'Manuel Neuer',
        end_player_id: '16980',
        end_player_name: 'Jürgen Klinsmann',
        contributor: 'jarvis',
    },
    '2026-07-05': {
        start_player_id: '2219',
        start_player_name: 'Philipp Lahm',
        end_player_id: '5817',
        end_player_name: 'Andrea Pirlo',
        contributor: 'jarvis',
    },
    '2026-07-04': {
        start_player_id: '206',
        start_player_name: 'Oliver Kahn',
        end_player_id: '5775',
        end_player_name: 'Fabio Cannavaro',
        contributor: 'jarvis',
    },
    '2026-07-03': {
        start_player_id: '3397',
        start_player_name: 'Paul Scholes',
        end_player_id: '3407',
        end_player_name: 'Ruud van Nistelrooy',
        contributor: 'jarvis',
    },
    '2026-07-02': {
        start_player_id: '3183',
        start_player_name: 'Patrick Vieira',
        end_player_id: '421727',
        end_player_name: 'Ronaldo Córdoba',
        contributor: 'jarvis',
    },
    '2026-07-01': {
        start_player_id: '3139',
        start_player_name: 'David Beckham',
        end_player_id: '101045',
        end_player_name: 'Ruud Gullit',
        contributor: 'jarvis',
    },
    '2026-06-30': {
        start_player_id: '3163',
        start_player_name: 'Frank Lampard',
        end_player_id: '68290',
        end_player_name: 'Neymar',
        contributor: 'jarvis',
    },
    '2026-06-29': {
        start_player_id: '3924',
        start_player_name: 'Didier Drogba',
        end_player_id: '38253',
        end_player_name: 'Robert Lewandowski',
        contributor: 'jarvis',
    },
    '2026-06-28': {
        start_player_id: '7607',
        start_player_name: 'Xavi',
        end_player_id: '74471',
        end_player_name: 'Marco van Basten',
        contributor: 'jarvis',
    },
    '2026-06-27': {
        start_player_id: '7600',
        start_player_name: 'Andrés Iniesta',
        end_player_id: '5803',
        end_player_name: 'Paolo Maldini',
        contributor: 'jarvis',
    },
    '2026-06-26': {
        start_player_id: '3207',
        start_player_name: 'Thierry Henry',
        end_player_id: '148455',
        end_player_name: 'Mohamed Salah',
        contributor: 'jarvis',
    },
    '2025-11-02': {
        start_player_id: '5950',
        start_player_name: 'Pep Guardiola',
        end_player_id: '39679',
        end_player_name: 'Marouane Fellaini',
        contributor: 'mushi',
    },
    '2025-11-01': {
        start_player_id: '4112',
        start_player_name: 'Rory Delap',
        end_player_id: '7451',
        end_player_name: 'Mikel Arteta',
        contributor: 'mushi',
    },
    '2025-10-31': {
        start_player_id: '44352',
        start_player_name: 'Luis Suárez',
        end_player_id: '6934',
        end_player_name: 'Tuncay Şanlı',
        contributor: 'mushi',
    },
    '2025-10-30': {
        start_player_id: '34870',
        start_player_name: 'Roberto Soldado',
        end_player_id: '27306',
        end_player_name: 'Mathieu Debuchy',
        contributor: 'mushi',
    },
    '2025-10-29': {
        start_player_id: '371998',
        start_player_name: 'Vinicius Junior',
        end_player_id: '72047',
        end_player_name: 'Iago Aspas',
        contributor: 'mushi',
    },
    '2025-10-28': {
        start_player_id: '145988',
        start_player_name: 'Wilfried Zaha',
        end_player_id: '1161',
        end_player_name: 'Javier Zanetti',
        contributor: 'mushi',
    },
    '2025-10-27': {
        start_player_id: '5023',
        start_player_name: 'Gianluigi Buffon',
        end_player_id: '7562',
        end_player_name: 'Santiago Cañizares',
        contributor: 'mushi',
    },
    '2025-10-26': {
        start_player_id: '7663',
        start_player_name: 'Joaquín',
        end_player_id: '197838',
        end_player_name: 'Jamie Vardy',
        contributor: 'mushi',
    },
    '2025-10-25': {
        start_player_id: '37148',
        start_player_name: 'Gabriel Agbonlahor',
        end_player_id: '503733',
        end_player_name: 'Anthony Gordon',
        contributor: 'mushi',
    },
    '2025-10-24': {
        start_player_id: '26399',
        start_player_name: 'Sergio Agüero',
        end_player_id: '31095',
        end_player_name: 'Nuri Şahin',
        contributor: 'mushi',
    },
    '2025-10-23': {
        start_player_id: '3373',
        start_player_name: 'Ronaldinho',
        end_player_id: '28990',
        end_player_name: 'Charlie Adam',
        contributor: 'mushi',
    },
    '2025-10-22': {
        start_player_id: '342229',
        start_player_name: 'Kylian Mbappé',
        end_player_id: '12000',
        end_player_name: 'Éric Cantona',
        contributor: 'mushi',
    },
    '2025-10-21': {
        start_player_id: '3366',
        start_player_name: 'Kaká',
        end_player_id: '937958',
        end_player_name: 'Lamine Yamal',
        contributor: 'mushi',
    },
    '2025-10-20': {
        start_player_id: '50202',
        start_player_name: 'Eden Hazard',
        end_player_id: '418560',
        end_player_name: 'Erling Haaland',
        contributor: 'mushi',
    },
    '2025-10-19': {
        start_player_id: '3109',
        start_player_name: 'Steven Gerrard',
        end_player_id: '568177',
        end_player_name: 'Cole Palmer',
        contributor: 'mushi',
    },
    '2025-10-18': {
        start_player_id: '3111',
        start_player_name: 'Zinedine Zidane',
        end_player_id: '3455',
        end_player_name: 'Zlatan Ibrahimović',
        contributor: 'mushi',
    },
    '2025-10-17': {
        start_player_id: '8198',
        start_player_name: 'Cristiano Ronaldo',
        end_player_id: '28003',
        end_player_name: 'Lionel Messi',
        contributor: 'mushi',
    },
    '2025-10-16': {
        start_player_id: '7767',
        start_player_name: 'Fernando Torres',
        end_player_id: '3332',
        end_player_name: 'Wayne Rooney',
        contributor: 'mushi',
    },
}
